### ISSUE TITLE
Non delimited bibtex fields make the parser crash

### ISSUE THREAD

**Issue by jlelong** [tamuratak/latex-utensils#7]
This is reported in James-Yu/LaTeX-Workshop/issues/1803.

Consider the following `test.bib` file

```bibtex
@reference{dictionary_of_contemporary_english,
    editor = "",
    edition = {Fourth edition},
    title = "Dictionary of Contemporary English",
    publisher = "Longman",
    year = 2003,
    ISBN = 1-405-80673-7
}
```

Running `luparse -i test.bib` returns

```
luparse.js:71
    throw e;
    ^
peg$SyntaxError: Expected "#", ",", "\r\n", "}", [ \t\n], or [0-9] but "-" found.
    at peg$buildStructuredError (/Users/jl/devel/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)
    at Object.peg$parse [as parse] (/Users/jl/devel/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)
    at Object.parse (/Users/jl/devel/latex-utensils/out/src/bibtex/bibtex_parser.js:23:30)
    at Object.<anonymous> (/Users/jl/devel/latex-utensils/out/src/bin/luparse.js:50:35)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  message: 'Expected "#", ",", "\\r\\n", "}", [ \\t\\n], or [0-9] but "-" found.',
```

**Comment by tamuratak** [comment]
`ISBN = 1-405-80673-7` is invalid. See http://www.bibtex.org/Format/.
